job_title:  # Должность (обязательное поле, должно совпадать с названием резюме)
  Программист Python

login:  # Логин: email или телефон (обязательное поле)
  alexneth93@gmail.com

keywords:
  - "Python разработчик Солар"

experience: # Требуемый опыт работы (обязательное поле) (может принимать только одно значение true)
  doesnt_matter: true  # Не имеет значения
  no_experience: false  # Нет опыта
  between_1_and_3: false  # От 1 года до 3 лет
  between_3_and_6: false  # От 3 до 6 лет
  6_and_more: false  # Более 6 лет

sort_by:  # Сортировать выдачу (обязательное поле) (может принимать только одно значение true)
  relevance: true  # по соответствию
  publication_time: false  # по дате изменения
  salary_desc: false  # по убыванию зарплат
  salary_asc: false  # по возрастанию зарплаты

output_period:  # Выводить (обязательное поле) (может принимать только одно значение true)
  all_time: true  # за всё время
  month: false  # за месяц
  week: false  # за неделю
  three_days: false  # за последние три дня
  one_day: false  # за сутки

output_size:  # Показывать на странице (обязательное поле) (может принимать только одно значение true)
  show_20: true
  show_50: false
  show_100: false
